services:
  env:
    build:
      context: "."
      # target: "boxenv"
      args:
        - "UID=${UID:-1000}"
        - "GID=${GID:-1000}"
    volumes:
      - ./output:/home/user/workdir/output
    command: /bin/bash
    stdin_open: true
    tty: true
    network_mode: "host"