services:
  dig-container:
    build:
      context: "."
      # target: "boxenv"
      args:
        - "UID=${UID:-1000}"
        - "GID=${GID:-1000}"
    volumes:
      - ./archive:/home/user/archive/
      - ./workdir:/home/user/workdir/
    command: /bin/bash
    stdin_open: true
    tty: true
    network_mode: "host"